name: Build and Deploy .NET Core API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    env:
      Solution_Name: CURDWithCqrsandRepository.sln  # Replace with your actual solution name

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x.x'  # Replace with your .NET Core version

    - name: Restore dependencies
      run: dotnet restore ${{ env.Solution_Name }}

    - name: Build the solution
      run: dotnet build ${{ env.Solution_Name }} --configuration Release --no-restore

    - name: Run Tests
      # You can skip this step if you don’t have tests
      run: dotnet test ${{ env.Solution_Name }} --no-restore --verbosity normal

    - name: Publish Web API
      run: dotnet publish CURDWithCqrsandRepository/CURDWithCqrsandRepository.csproj -c Release -o ./publish

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'YourAppServiceName'  # Replace with your Azure WebApp name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'
